FPTBookStore/Controllers/CustomerController.cs
using KTBook.Models;
using KTBook.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using System.Security.Claims;
using Newtonsoft.Json;

namespace KTBook.Controllers
{
    public class CustomerController : Controller
    {

        public const string CARTKEY = "cart";
        List<CartItem> GetCartItems()
        {
            var session = HttpContext.Session;
            string jsoncart = session.GetString(CARTKEY);
            if (jsoncart != null)
            {
                return JsonConvert.DeserializeObject<List<CartItem>>(jsoncart);
            }
            return new List<CartItem>();
        }

        // Xóa cart khỏi session
        void ClearCart()
        {
            var session = HttpContext.Session;
            session.Remove(CARTKEY);
        }

        // Lưu Cart (Danh sách CartItem) vào session
        void SaveCartSession(List<CartItem> ls)
        {
            var session = HttpContext.Session;
            string jsoncart = JsonConvert.SerializeObject(ls);
            session.SetString(CARTKEY, jsoncart);
        }
        private readonly ApplicationDbContext context;
        public CustomerController(ApplicationDbContext dbContext)
        {
            context = dbContext;

        }
        [Route("/")]
        public IActionResult Index()
        {
            var products = context.Product.ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View(products);
        }


        public IActionResult Index2(int? id)
        {
            var products = context.Product.ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            var productSearch = context.Category.Include(c => c.Products).FirstOrDefault(c => c.Id == id);
            return View(productSearch);
        }
        [HttpPost]
        public IActionResult Search(string search)
        {
            var products = context.Product.Where(p => p.Name.Contains(search)).ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            TempData["search"] = search;

            return View("Index", products);
        }
        public IActionResult Details(int? id)
        {
            var products = context.Product.ToList();
            var item = products.FirstOrDefault(c => c.Id == id);
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View(item);
        }

        [Authorize(Roles = "Customer,Administrator")]
        public IActionResult AddtoCart(int? id)
        {
            var product = context.Product
        .Where(p => p.Id == id)
        .FirstOrDefault();
            if (product == null)
                return NotFound("Không có sản phẩm");

            // Xử lý đưa vào Cart ...
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.product.Id == id);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cartitem.Quantity++;
            }
            else
            {
                //  Thêm mới
                cart.Add(new CartItem() { Quantity = 1, product = product });
            }

            // Lưu cart vào Session
            SaveCartSession(cart);
            // Chuyển đến trang hiện thị Cart
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ViewCart()
        {
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View(GetCartItems());
        }

        [Route("/updatecart", Name = "updatecart")]
        [HttpPost]
        public IActionResult UpdateCart(int productid, int quantity)
        {
            // Cập nhật Cart thay đổi số lượng quantity ...
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.product.Id == productid);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cartitem.Quantity = quantity;
            }
            SaveCartSession(cart);
            // Trả về mã thành công (không có nội dung gì - chỉ để Ajax gọi)
            return Ok();
        }
        [Route("/removecart/{productid:int}", Name = "removecart")]
        public IActionResult RemoveCart([FromRoute] int productid)
        {
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.product.Id == productid);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cart.Remove(cartitem);
            }

            SaveCartSession(cart);
            return RedirectToAction(nameof(ViewCart));
        }
        public IActionResult UserView()
        {
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            var claimIdentity = (ClaimsIdentity)User.Identity;

            var claims = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string currentUserId = claims.Value;
            //var user = _context.Users.OfType<ApplicationUser>().FirstOrDefault(u => u.UserName == userName);
            ApplicationUser currentUser = (ApplicationUser)context.Users.FirstOrDefault(x => x.Id == currentUserId);

            ViewBag.Img = currentUser.Image;
            ViewBag.Id = currentUser.Id;
            ViewBag.Email = currentUser.Email;
            ViewBag.UserName = currentUser.UserName;
            ViewBag.Fullname = currentUser.FullName;
            ViewBag.Address = currentUser.Address;
            ViewBag.Dob = currentUser.DoB;
            return View();
        }
        public IActionResult Checkout()
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string currentUserId = claims.Value;

            // caculate total price
            var cart = GetCartItems();
            double total = 0;
            foreach (var item in cart)
            {
                total += (double)(item.product.Price * item.Quantity);
            }

            for (int i = 0; i < cart.Count; i++)
            {
                var order = new Order()
                {
                    UserId = currentUserId,
                    ProductId = cart[i].product.Id,
                    ProductName = cart[i].product.Name,
                    image = cart[i].product.Image,
                    Price = (int)cart[i].product.Price,
                    Quantity = cart[i].Quantity,
                    TotalPrice = total,

                };
                context.Order.Add(order);
                context.SaveChanges();
            }
            ClearCart();
            return RedirectToAction(nameof(Index));

        }
        public IActionResult ViewOrder()
        {
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string currentUserId = claims.Value;
            //int UsrID = Int32.Parse(currentUserId);
            string UsrID = currentUserId;
            var orders = context.Order.ToList();
            var FindOrder = context.Order.Where(p => p.UserId.Contains(currentUserId)).ToList();
            return View("ViewOrder", FindOrder);

        }
    }

}

FPTBookStore/Controllers/ProductController.cs
using KTBook.Data;
using KTBook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;


namespace KTBook.Controllers
{


    public class ProductsController : Controller
    {

        private readonly ApplicationDbContext context;


        public ProductsController(ApplicationDbContext dbContext)
        {
            context = dbContext;

        }
        protected UserManager<ApplicationUser> UserManager { get; set; }



        [Authorize(Roles = "Owner")]
        public IActionResult Index()
        {
            var products = context.Product.ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View(products);
            //ViewData["CategoryId"] = new SelectList(context.Set<Category>(), "Id", "Id");
            //return View();
        }

        [Authorize(Roles = "Owner")]
        [HttpGet]

        public IActionResult Create()
        {
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            //if (categories == null)
            //{
            //    Console.WriteLine("Error");
            //}
            //else
            //{
            //    ViewBag.Categories = categories;
            //}
            return View();
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                TempData["Message"] = "Create product successfully";
                context.Product.Add(product);
                context.SaveChanges();
                return Redirect("/products");
            }
            return View();
        }
        [Authorize(Roles = "Owner")]
        [HttpGet]
        public IActionResult Details(int? id)
        {
            var products = context.Product.ToList();
            var item = products.Find(p => p.Id == id);
            return View(item);
        }
        [Authorize(Roles = "Owner")]
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var products = context.Product.ToList();
            var item = products.Find(p => p.Id == id);
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View(item);
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Update(Product product)
        {
            if (ModelState.IsValid)
            {
                TempData["Message"] = "Update product successfully";
                context.Product.Update(product);
                context.SaveChanges();
                return Redirect("/products");

            }
            return View();
        }
        [Authorize(Roles = "Owner")]
        [HttpGet]
        public IActionResult Confirm(int? id)
        {
            var products = context.Product.ToList();
            var item = products.Find(p => p.Id == id);
            return View(item);
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Delete(Product product)
        {
            TempData["Message"] = "Delete product successfully";
            context.Product.Remove(product);
            context.SaveChanges();
            return Redirect("/products");
        }

        public IActionResult UserView()
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;

            var claims = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string currentUserId = claims.Value;
            ApplicationUser currentUser = (ApplicationUser)context.Users.FirstOrDefault(x => x.Id == currentUserId);

            ViewBag.Img = currentUser.Image;
            ViewBag.Id = currentUser.Id;
            ViewBag.Email = currentUser.Email;
            ViewBag.UserName = currentUser.UserName;
            ViewBag.Fullname = currentUser.FullName;
            ViewBag.Address = currentUser.Address;
            ViewBag.Dob = currentUser.DoB;
            return View(currentUser);
        }

        [HttpPost]
        public IActionResult Search(string search)
        {
            var products = context.Product.Where(p => p.Name.Contains(search)).ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            
            return View("Index", products);
        }
        public IActionResult SortDESC()
        {
            var products = context.Product.OrderByDescending(p => p.Quantity).ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View("Index", products);
        }
        public IActionResult SortASC()
        {
            var products = context.Product.OrderBy(p => p.Quantity).ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View("Index", products);
        }
    }


}

FPTBookStore/Views/Customer/Checkout.cshtml
<h1>Checkout</h1>

FPTBookStore/Views/Customer/Details.cshtml
@model KTBook.Models.Product

@{
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";

}

<div class="products">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-xs-12">
                <div>
                    <img src="~/img/@Model.Image" alt="" class="img-fluid wc-image">
                </div>
            </div>
            <div class="col-md-8 col-xs-12">
                <form action="#" method="post" class="form">
                    <h2>@Model.Name</h2>
                    <br>
                    <p class="lead">
                        <small><del> $999</del></small><strong class="text-primary">$@Model.Price</strong>
                    </p>
                    <br>
                    <p class="lead">
                        Description: @Model.Description
                    </p>
                    <br>
                    <div class="row">
                        <div class="col-sm-8">
                            <label class="control-label">Quantity</label>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="1">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <a asp-controller="Customer" asp-action="AddtoCart" asp-route-Id="@Model.Id" class="btn btn-primary btn-block">Add to Cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

FPTBookStore/Views/Customer/Index.cshtml
@model List<Product>
@{
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
    ViewData["Title"] = "Page Title";
}

<div class="page-heading about-heading header-text" style="background-image: url(assets/images/Book1.jpg);">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-content">
                    <h4>Bringing knowledge to everyone</h4>
                    <h2>KTBook Store</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="products">
    <div class="container">
        <div class="row">

            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="product-item">
                        <a asp-controller="Customer" asp-action="Details" asp-route-id="@item.Id"><img src="~/img/@item.Image" alt="project image cap" style="height: 351px; width:344px"></a>
                        <div class="down-content">
                            <a asp-controller="Products" asp-action="Details" asp-route-id="@item.Id"><h4>@item.Name</h4></a>
                            <h6>Price: $@item.Price</h6>
                        </div>
                    </div>
                </div>
            }



            <div class="col-md-12">
                <ul class="pages">
                    <li><a href="#">1</a></li>
                    <li class="active"><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

FPTBookStore/Views/Customer/Index2.cshtml
@model KTBook.Models.Category
@{
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
    ViewData["Title"] = "Page Title";
}

@*View By Category*@
<div class="container-fluid mm-active" style="padding-bottom: 5%; background-color: darksalmon">
    <div class="wrapper mm-show">
        <div class="content-page">
            <div class="content">
                <div class="row">
                    @foreach (var item in Model.Products)
                    {
                        <div class="col-md-6 col-xl-3">
                            <!-- project card -->
                            <div class="card d-block text-dark" style="width: 300px; height: 300px; margin: 50px 30px; box-shadow: 0 10px 15px 0 rgba(0, 0, 0, 0.25),0 5px 15px 0 rgba(0, 0, 0, 0.12)">
                                <!-- project-thumbnail -->
                                <a asp-controller="Customer" asp-action="Details" asp-route-id="@item.Id">
                                    <img class="card-img-top" src="~/img/@item.Image"
                                         alt="project image cap" style="height: 100%; width:100%">

                                </a>
                                <p style="text-align: center;color: black;">Name: @item.Name</p>
                                <p style="text-align: center;color: black;">Price: @item.Price</p>
                                @{
                                    Random rnd = new Random();
                                    // This will return either 1 to 100 randomly.
                                    int question = rnd.Next(1, 100);
                                }
                                <p class="mb-2 font-weight-bold">
                                    Most people like <span class="float-right">45%</span>
                                </p>
                                <div class="progress progress-sm">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="45"
                                         aria-valuemin="0" aria-valuemax="100" style="width: 45%;">
                                    </div><!-- /.progress-bar -->
                                </div><!-- /.progress -->
                            </div> <!-- end card-->
                        </div>
                    }
                    <!-- end col -->
                </div>
            </div>
        </div>
    </div>
</div>

FPTBookStore/Views/Customer/UserView.cshtml
@model ApplicationUser

@{
    //Layout = "~/Views/Shared/_CustomerLayout.cshtml";
    ViewData["Title"] = "Page Title";
}

<div class="row">
    <div class="col-xl-4 col-lg-5">
        <div class="card text-center">
            <div class="card-body">
                <img src="@ViewBag.Img" class="img-thumbnail" alt="profile-image">

                <h4 class="mb-0 mt-2" >@ViewBag.Fullname</h4>


                <button type="button" class="btn btn-success btn-sm mb-2" style="margin-top:20px">Follow</button>
                <button type="button" class="btn btn-danger btn-sm mb-2" style="margin-top:20px">Message</button>

                <div class="text-left mt-3">
                    <h4 class="font-13 text-uppercase" style="text-align: center">About Me :</h4>
                    <p class="text-muted font-13 mb-3">
                        Hi I'm @ViewBag.Fullname, nice to meet you!.
                    </p>
                    <p class="text-muted mb-2 font-13">
                        <strong>Full Name :</strong> <span class="ml-2">
                            @ViewBag.Fullname
                        </span>
                    </p>

                   @* <p class="text-muted mb-2 font-13">
                        <strong>Mobile :</strong><span class="ml-2">
                            (123)
                            123 1234
                        </span>
                    </p>*@

                    <p class="text-muted mb-2 font-13"><strong>Email :</strong> <span class="ml-2 ">@ViewBag.Email</span></p>
                    <p class="text-muted mb-2 font-13"><strong>Username :</strong> <span class="ml-2 ">@ViewBag.UserName</span></p>
                    <p class="text-muted mb-1 font-13"><strong>Date of Birth :</strong> <span class="ml-2">@ViewBag.DoB</span></p>
                    <p class="text-muted mb-1 font-13"><strong>Location :</strong> <span class="ml-2">@ViewBag.Address</span></p>
                </div>

                @*Communication*@
                <ul class="social-list list-inline mt-3 mb-0">
                    <li class="list-inline-item">
                        <a href="javascript: void(0);" class="social-list-item border-primary text-primary"><i class="mdi mdi-facebook"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="javascript: void(0);" class="social-list-item border-danger text-danger"><i class="mdi mdi-google"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="javascript: void(0);" class="social-list-item border-info text-info"><i class="mdi mdi-twitter"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="javascript: void(0);" class="social-list-item border-secondary text-secondary"><i class="mdi mdi-github-circle"></i></a>
                    </li>
                </ul>
            </div> <!-- end card-body -->
        </div> <!-- end card -->
        <!-- Messages-->
        <div class="card">
            <!-- end card-body-->
        </div> <!-- end card-->

    </div> <!-- end col-->

    <div class="col-xl-8 col-lg-7">
        <div class="card">
            <div class="card-body">
                <ul class="nav nav-pills bg-nav-pills nav-justified mb-3">
                    <li class="nav-item">
                        <a href="#aboutme" data-toggle="tab" aria-expanded="false" class="nav-link rounded-0 active">
                            History Order
                        </a>
                    </li>


                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="aboutme">

                        <h5 class="text-uppercase">
                            <i class="mdi mdi-briefcase mr-1"></i>
                            Order
                        </h5>

                        <div class="timeline-alt pb-0">
                            <div class="timeline-item">
                                <i class="mdi mdi-circle bg-info-lighten text-info timeline-icon"></i>
                                <div class="timeline-item-info">
                                    <h5 class="mt-0 mb-1">Total Order in 2020</h5>
                                    @*<p class="font-14">websitename.com <span class="ml-2 font-12">Year: 2015 - 18</span></p>*@
                                    <p class="text-muted mt-2 mb-0 pb-3">
                                        In 2020, the customer bought 200 candies.
                                    </p>
                                </div>
                            </div>

                            <div class="timeline-item">
                                <i class="mdi mdi-circle bg-primary-lighten text-primary timeline-icon"></i>
                                <div class="timeline-item-info">
                                    <h5 class="mt-0 mb-1">Total Order in 2021</h5>
                                    @*<p class="font-14">Software Inc. <span class="ml-2 font-12">Year: 2012 - 15</span></p>*@
                                    <p class="text-muted mt-2 mb-0 pb-3">
                                        In 2021, the customer bought 20 phones.
                                    </p>

                                </div>
                            </div>

                            <div class="timeline-item">
                                <i class="mdi mdi-circle bg-info-lighten text-info timeline-icon"></i>
                                <div class="timeline-item-info">
                                    <h5 class="mt-0 mb-1">Total Order in 2022</h5>
                                    @*<p class="font-14">Coderthemes Design LLP <span class="ml-2 font-12">Year: 2010 - 12</span></p>*@
                                    <p class="text-muted mt-2 mb-0 pb-2">
                                        In 2022, the customer bought 20 laptops.
                                    </p>
                                </div>
                            </div>

                            <div class="timeline-item">
                                <i class="mdi mdi-circle bg-info-lighten text-info timeline-icon"></i>
                                <div class="timeline-item-info">
                                    <h5 class="mt-0 mb-1">Total Order in 2023 </h5>
                                    @*<p class="font-14">Coderthemes Design LLP <span class="ml-2 font-12">Year: 2010 - 12</span></p>*@
                                    <p class="text-muted mt-2 mb-0 pb-2">
                                            In 2023, the customer bought 20 ipods.
                                    </p>
                                </div>
                            </div>

                        </div>
                        <!-- end timeline -->




                    </div> <!-- end tab-pane -->
                    <!-- end about me section content -->

           
                    <!-- end timeline content-->

        
                    <!-- end settings content-->

                </div> <!-- end tab-content -->
            </div> <!-- end card body -->
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>

FPTBookStore/Views/Customer/ViewOrder.cshtml
@model List<Order>
@{
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

@{
    double t = 0;
    @foreach (var item in Model)
    {
         t += item.TotalPrice;
    }
}
 
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body" style="background-color: beige;">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="table-responsive">
                            <table class="table table-borderless table-centered mb-0">
                                <thead class="thead-light">
                                    <tr>
                                        <th>Product</th>
                                        <th>Product Name</th>
                                        <th>Unit Price</th>
                                        <th>Quantity</th>
                                        
                                        <th style="width: 50px;"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach(var item in Model)
                                    {
                                    <tr>
                                        <td>
                                                <img src="~/img/@item.image" alt="product-image" title="product-image" class="rounded-circle" height="50" width="50">
                                           @* <p class="m-0 d-inline-block align-middle font-16">
                                                <a asp-controller="Customer" asp-action="Details" asp-route-Id="@item.ProductId" class="text-body">@item.ProductName</a>
                                                <br>
                                            </p>*@
                                        </td>
                                            <td>
                                                @*@item.ProductName*@
                                                <a asp-controller="Customer" asp-action="Details" asp-route-Id="@item.ProductId" class="text-body">@item.ProductName</a>

                                            </td>
                                        <td>
                                            $@item.Price
                                        </td>
                                        <td>
                                            @item.Quantity
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div> <!-- end table-responsive-->
                        <!-- Add note input-->
                       

                        <!-- action buttons-->
                        <div class="row mt-4">
@*                            <div class="col-sm-6">
                                <a asp-controller="Customer" asp-action="Index" class="btn text-muted d-none d-sm-inline-block btn-link font-weight-semibold">
                                    <i class="mdi mdi-arrow-left" style="color: orange"></i> Back to Continue Shopping :)
                                </a>
                            </div>*@ <!-- end col -->
                            <div class="col-sm-6">
                                <div class="text-sm-right">
                                </div>
                            </div> <!-- end col -->
                        </div> <!-- end row-->
                    </div>
                    <!-- end col -->

                    <div class="col-lg-4">
                        <div class="border p-3 mt-4 mt-lg-0 rounded">
                            <h4 class="header-title mb-3" style="text-align: center; color: red">Order Summary</h4>

                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <tbody>
                                        <tr>
                                            <th>Total :</th>
                                            <th>$@t</th>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <!-- end table-responsive -->
                        </div>
                        <div class="input-group mt-3">
                        </div>
                    </div> <!-- end col -->
                </div> <!-- end row -->
            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>
@*Button*@
<div class="">
    <a asp-controller="Customer" asp-action="Index" class="btn btn-success" style="margin-left: 35%;">
        <i class="mdi mdi-arrow-left" style="text-align: center"></i> Back to Continue Shopping :)
    </a>
</div>